#!/usr/bin/env php
<?php
function copy_dir($src, $dst)
{
    if (is_link($src)) {
        symlink(readlink($src), $dst);
    } elseif (is_dir($src)) {
        @mkdir($dst);
        foreach (scandir($src) as $file) {
            if ($file != '.' && $file != '..') {
                copy_dir("$src/$file", "$dst/$file");
            }
        }
    } elseif (is_file($src)) {
        copy($src, $dst);
    } else {
        echo "WARNING: Cannot copy $src (unknown file type)\n";
    }
}

function replace_hook_string(string $string, $from, $to): string
{
    $walk = function (&$value) {
        $value = "{{{$value}}}";
    };
    if (is_string($from)) {
        $from = "{{{$from}}}";
    } elseif (is_array($from)) {
        array_walk($from, $walk);
    }
    return str_replace($from, $to, $string);
}

$standard_template = file_get_contents(__DIR__ . '/templates/standard/Dockerfile');
$standard_tags = ['8.2', '8.3', '8.4', 'latest'];
foreach ($standard_tags as $tag) {
    $content = replace_hook_string($standard_template, 'tag', $tag);
    @mkdir(__DIR__ . '/' . $tag);
    file_put_contents(__DIR__ . '/' . $tag . '/Dockerfile', $content);
}

// generate alpine
$alpine_template = file_get_contents(__DIR__ . '/templates/alpine/Dockerfile');
$alpine_tags = ['8.2-alpine', '8.3-alpine', '8.4-alpine', 'latest-alpine'];
foreach ($alpine_tags as $tag) {
    $content = replace_hook_string($alpine_template, 'tag', $tag);
    @mkdir(__DIR__ . '/' . $tag);
    file_put_contents(__DIR__ . '/' . $tag . '/Dockerfile', $content);
}
